name: example
description: An example Flutter project to demonstrate the usage of cached_build_runner.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  json_serializable: ^6.6.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  auto_mappr_annotation: 2.1.0

dev_dependencies:
  build_runner: ^2.3.3
  cached_build_runner:
    path: ../
  auto_mappr: 2.2.0

  flutter_lints: ^2.0.0
  freezed: ^2.4.6

flutter:
  uses-material-design: true
