name: build_cache
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  args: ^2.4.0
  crypto: ^3.0.2
  hive: ^2.2.3
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0