name: cached_build_runner
description: Optimizes the build_runner by caching generated codes for non changed .dart files
version: 0.0.3

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  args: 2.4.0
  crypto: 3.0.1
  hive: 2.2.3
  path: 1.8.2
  redis: 3.1.0

dev_dependencies:
  lints: 2.0.0
  test: 1.16.0